import { Share_Tech } from 'next/font/google'

import './globals.scss'

const font = Share_Tech({ weight: ['400'], subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={font.className}>
        <main className='layout'>{children}</main>
      </body>
    </html>
  )
}
